name: Fill IELTS Words

on:
  schedule:
    - cron: "0 16 * * *"          # 每小时整点运行（UTC）
  workflow_dispatch:             # 允许手动触发
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install openai==1.30.5 httpx==0.27.* requests python-dotenv

      - name: Run script
        env:
          SF_API_KEY: ${{ secrets.SF_API_KEY }}
          NOTION_TOKEN: ${{ secrets.NOTION_TOKEN }}
          DATABASE_ID: ${{ secrets.DATABASE_ID }}
        run: |
          python fill_words.py